set -U fish_color_autosuggestion 969896
set -U fish_color_command c397d8
set -U fish_color_comment e7c547
set -U fish_color_cwd 96a
set -U fish_color_cwd_root red
set -U fish_color_end c397d8
set -U fish_color_error d54e53
set -U fish_color_escape cyan
set -U fish_color_history_current cyan
set -U fish_color_host \x2do\x1ecyan
set -U fish_color_match cyan
set -U fish_color_normal normal
set -U fish_color_operator cyan
set -U fish_color_param 7aa6da
set -U fish_color_quote b9ca4a
set -U fish_color_redirection 70c0b1
set -U fish_color_search_match \x2d\x2dbackground\x3dpurple
set -U fish_color_status red
set -U fish_color_user \x2do\x1egreen
set -U fish_color_valid_path \x2d\x2dunderline
